<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24742" started-at="2019-01-22T08:23:12Z" finished-at="2019-01-22T08:23:37Z">
    <groups>
    </groups>
    <test name="Login Page Tests" duration-ms="14199" started-at="2019-01-22T08:23:12Z" finished-at="2019-01-22T08:23:26Z">
      <class name="Blume2000.loginPageTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:Blume2000.loginPageTest@62ddbd7e]" name="openBrowser" is-config="true" duration-ms="8867" started-at="2019-01-22T13:53:12Z" finished-at="2019-01-22T13:53:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:Blume2000.loginPageTest@62ddbd7e]" name="loginTest" duration-ms="1913" started-at="2019-01-22T13:53:21Z" data-provider="testData" finished-at="2019-01-22T13:53:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[testpassword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ich2 bin bereits Kunde bei Blume2000.de] but found [Ich bin bereits Kunde bei Blume2000.de]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ich2 bin bereits Kunde bei Blume2000.de] but found [Ich bin bereits Kunde bei Blume2000.de]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Blume2000.loginPageTest.loginTest(loginPageTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:Blume2000.loginPageTest@62ddbd7e]" name="loginTest" duration-ms="1562" started-at="2019-01-22T13:53:23Z" data-provider="testData" finished-at="2019-01-22T13:53:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test2@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test2password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ich2 bin bereits Kunde bei Blume2000.de] but found [Ich bin bereits Kunde bei Blume2000.de]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ich2 bin bereits Kunde bei Blume2000.de] but found [Ich bin bereits Kunde bei Blume2000.de]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Blume2000.loginPageTest.loginTest(loginPageTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Blume2000.loginPageTest@62ddbd7e]" name="closeBrowser" is-config="true" duration-ms="1204" started-at="2019-01-22T13:53:25Z" finished-at="2019-01-22T13:53:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Blume2000.loginPageTest -->
    </test> <!-- Login Page Tests -->
    <test name="Home Page Tests" duration-ms="10492" started-at="2019-01-22T08:23:26Z" finished-at="2019-01-22T08:23:37Z">
      <class name="Blume2000.homePageTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:Blume2000.homePageTest@1ff4931d]" name="openBrowser" is-config="true" duration-ms="7866" started-at="2019-01-22T13:53:26Z" finished-at="2019-01-22T13:53:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="registerationTest()[pri:0, instance:Blume2000.homePageTest@1ff4931d]" name="registerationTest" duration-ms="1684" started-at="2019-01-22T13:53:34Z" finished-at="2019-01-22T13:53:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerationTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Blume2000.homePageTest@1ff4931d]" name="closeBrowser" is-config="true" duration-ms="941" started-at="2019-01-22T13:53:36Z" finished-at="2019-01-22T13:53:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Blume2000.homePageTest -->
    </test> <!-- Home Page Tests -->
  </suite> <!-- Suite -->
</testng-results>
